apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-controller
  labels:
    name: tomcat
spec:
  replicas: 1
  selector:
    name: tomcat
  template:
    metadata:
      labels:
        name: tomcat
    spec:
      containers:
      -
        name: tomcat
        image: tomcat:8.0
        ports:
        -
          containerPort: 8080
          protocol: "TCP"
