apiVersion: v1
kind: Service
metadata:
  labels:
    name: tomcat
  name: tomcat-service
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    # ports that this service should serve on
    -
      name: 'http'
      port: 8080
      targetPort: 8080
      nodePort: 32001
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: tomcat